
from dlvc.dataset import Dataset
from dlvc.datasets.pets import PetsDataset
import random
import types
import numpy as np
from collections import namedtuple

Batch = namedtuple('Batch', ['dat', 'labels', 'idx'])

class Batch:
    '''
    A (mini)batch generated by the batch generator.
    '''

    def __init__(self):
        '''
        Ctor.
        '''

        self.data = None
        self.label = None
        self.idx = None

class BatchGenerator:
    '''
    Batch generator.
    Returned batches have the following properties:
      data: numpy array holding batch data of shape (s, SHAPE_OF_DATASET_SAMPLES).
      labels: numpy array holding batch labels of shape (s, SHAPE_OF_DATASET_LABELS).
      idx: numpy array with shape (s,) encoding the indices of each sample in the original dataset.
    '''

    def __init__(self, dataset: Dataset, num: int, shuffle: bool, op: types.FunctionType = None):

        self.batches = []

        data = []
        label = []
        indices = []


        if shuffle:
            data = random.shuffle(dataset)
            for i in range(0, dataset.__len__()):
                indices.append(data.__getitem__(i)[0])
                data.append(op(data.__getitem__(i)[1]))
                label.append(data.__getitem__(i)[2])

            for i in range(0, dataset.__len__(), num):
                batch = Batch(dat=data[i:i + num][1], labels=label[i:i + num][2], idx=indices[i:i + num][0])
                self.batches.append(batch)


        else:
            for i in range(0, dataset.__len__()):
                indices.append(dataset.__getitem__(i)[0])
                data.append(op(dataset.__getitem__(i)[1]))
                label.append(dataset.__getitem__(i)[2])

            for i in range(0, self.dataset.__len__(), num):
                batch = Batch(dat=data[i:i + num][1], labels=label[i:i + num][2], idx=indices[i:i + num][0])
                self.batches.append(batch)

        '''
        ???? shouldn`t this have PetsDataset instead of Dataset as argument???
        Ctor.
        Dataset is the dataset to iterate over.
        num is the number of samples per batch. the number in the last batch might be smaller than that.
        shuffle controls whether the sample order should be preserved or not.
        op is a function to apply to input samples.
        Raises TypeError on invalid argument types.
        Raises ValueError on invalid argument values, such as if num is > len(dataset).
        '''

        # TODO implement

        pass

    def __len__(self) -> int:
        '''
        Returns the number of batches generated per iteration.
        '''

        return len(self.batches)

        pass

    def __iter__(self) -> types.GeneratorType:
        '''
        Iterate over the wrapped dataset, returning the data as batches.
        '''
        for i in range(0, self.batches.__len__()):
            yield self.batches[i]

        # The "yield" keyword makes this easier

        pass
